name: TESTING

on:
   push:
      branches: [master]
   pull_request:
      branches: ["*"]

jobs:
   unittests:
      runs-on: ubuntu-16.04
      steps:
         - name: Cloning Repository
           uses: actions/checkout@v1
         - name: Configuring dotnetSDK
           uses: actions/setup-java@v1
           with:
              java-version: 1.8
         - name: Run unittests
           run: mvn test
